version: '3'
services:
  apache:
    image: 'php:7.4-apache'
    build:
      dockerfile: ./dockerfile
    container_name: submarino_php
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    links:
      - db
      

  db:
    container_name: submarino_db  
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_development
